In [2]:
import numpy as np
import pandas as pd

In [12]:
user_action = pd.read_csv('./user_action.csv')
user_action.head(5)

user_id          int64
item_id          int64
behavior_type    int64
item_category    int64
time               str
dtype: object

In [16]:
user_action.dtypes
user_action['time'].dt.month.head(5)

0    12
1    12
2    12
3    12
4    12
Name: time, dtype: int32

In [14]:
user_action['time']=pd.to_datetime(user_action['time'])

In [ ]:
#检验是否有空值

In [8]:
user_action.loc[user_action['user_id'].isnull()]
user_action.loc[user_action['item_id'].isnull()]
user_action.loc[user_action['behavior_type'].isnull()]
user_action.loc[user_action['item_category'].isnull()]
user_action.loc[user_action['time'].isnull()]

Empty DataFrame
Columns: [user_id, item_id, behavior_type, item_category, time]
Index: []

In [ ]:
#检验是否有异常值

In [11]:
user_action.query('behavior_type<1 or behavior_type>4').head(5)

Empty DataFrame
Columns: [user_id, item_id, behavior_type, item_category, time]
Index: []

In [20]:
small_user = user_action.iloc[:2000]
small_user.to_csv("../small_user.csv",index=False)

In [24]:
print(user_action['time'].max())
user_action['time'].min()

2014-12-18 23:00:00

Timestamp('2014-11-18 00:00:00')

In [30]:
len(user_action['item_category'].unique())

8916